spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8080
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
